### PR TITLE
add JSX fragments support

### PR DESCRIPTION
**Pull request by sammysaglam**
- Added JSX fragments support, e.g. `<>this should be translated</>`
- Upgraded eslint so it can parse JSX fragments
- Add a simple test using a fragment

@blainemuri

### CODE REVIEW

**Comment by blainemuri** [comment]
Hey @sammysaglam I missed this coming through in my notifications. Will take a look within the next week and get this merged in as soon as possible. Thanks so much for submitting a pull request!

**Comment by sammy-at-fonoa** [comment]
@blainemuri just flagging this PR in case you get some time to review & merge

**Comment by sammysaglam** [comment]
@blainemuri just flagging this PR in case you get some time to review & merge

**Review by malakhov-dmitrii — APPROVED** [review]
LGTM 🤝

**Comment by CruseCtrl** [comment]
@blainemuri any word on this?

**Review by CruseCtrl — APPROVED** [review]

**Comment by CruseCtrl** [comment]
@blainemuri I'd appreciate it if this could be merged, please :)

**Review by IsaacClem — APPROVED** [review]

**Comment by IsaacClem** [comment]
@blainemuri any chance this could be merged soon please?

**Review by reececoombes — APPROVED** [review]

**Comment by reececoombes** [comment]
@blainemuri This would be really handy on my current project, is there any way this could get merged fairly soon? 🤞 Thanks!

**Comment by CruseCtrl** [comment]
@blainemuri is there anything I can do to help this get moved along?

**Comment by sammysaglam** [comment]
closing this PR because react-intl has their own eslint plugins for this, and this doesnt seem like it's going to get merged anytime soon

**Pull request closed without merging**
